services:
  - type: web
    name: clothncare
    runtime: docker
    region: oregon
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: clothncare-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true

databases:
  - name: clothncare-db
    plan: free
    region: oregon
    majorVersion: "15"
